# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /pr/:categories/index.html
relative_permalinks: true

# Setup
title:               Aquent Gymnasium Press Releases
url: "http://gymnasium.github.io/pr"
baseurl: "/pr"

# Custom vars

version:             1.0.0

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
